name: CI

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

#      - name: Make application.properties
#        run: |
#          cd ./src/main/resources
#          touch ./application.properties
#
#          echo "${{ secrets.TEST_DATABASE_PROPERTIES }}" >> ./application.properties
#        shell: bash

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'ebdb'
          mysql user: 'SJ'
          mysql password: ${{ secrets.TEST_DATASOURCE_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
