name: CI

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup MySQL
        uses: samin/mysql-action@v2
        with:
          character set server: 'utf8'
          mysql entryPoint: ${{secrets.TEST_DATASOURCE_HOST}}
          mysql database: ${{secrets.TEST_DATASOURCE_URL}}
          mysql user: ${{secrets.TEST_DATASOURCE_USERNAME}}
          mysql password: ${{secrets.TEST_DATASOURCE_PASSWORD}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
