name: CI

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          host port: 3306
          character set server: 'utf8'
#          args: --character-set-server=utf8 --mysql-host=${{ secrets.TEST_DATASOURCE_HOST }}
          mysql database: ebdb
          mysql user: SJ
          mysql password: ${{secrets.TEST_DATASOURCE_PASSWORD}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build
