name: CI

on:
  push:
    branches: [ main ]

#permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

#      - name: Shutdown Ubuntu MySQL (SUDO)
#        run: sudo service mysql stop

      - name: Use Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

#      - name: Set YML
#        run: |
#          mkdir -p src/main/resources
#          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
#          find src

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build